all:
	g++ CLIENT.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/client
	g++ SERVER.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/server -lseccomp
	g++ SUPER_SERVER.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/super_server
	