all:
	g++ CLIENT.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/client
	g++ SERVER.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/server -lseccomp -l sqlite3
	g++ SUPER_SERVER.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/super_server -l sqlite3
	g++ DATABASE_SERVER.cpp -std=c++14 -o /home/pratyush/Documents/Sharing_Hub/BINARY/database_server -l sqlite3